### ISSUE TITLE
extends node_modules json with same name dir results error

### ISSUE THREAD

**Issue by JounQin** [privatenumber/get-tsconfig#22]
```json
{
  "node_modules/@1stg/tsconfig/package.json": {
    "name": "@1stg/tsconfig"
  },
  "node_modules/@1stg/tsconfig/lib/.gitkeep": "",
  "node_modules/@1stg/tsconfig/lib.json": {
    "compilerOptions": {
      "jsx": "react-jsx"
    }
  },
  "tsconfig.json": {
    "extends": "@1stg/tsconfig/lib"
  }
}
```

```log
Error: File '@1stg/tsconfig/lib' not found.
    at null.x (/workspace/get-tsconfig/dist/index.js:3:5193)
    at null.I (/workspace/get-tsconfig/dist/index.js:3:5895)
    at null.ie (/workspace/get-tsconfig/dist/index.js:3:6878)
    at null.<anonymous> (/workspace/get-tsconfig/tests/specs/extends.spec.ts:382:22)
    at null.<anonymous> (/workspace/get-tsconfig/node_modules/.pnpm/manten@0.1.0/node_modules/manten/dist/index.js:1:676)
```

See #21 for reproduction details.

**Comment by JounQin** [comment]
close in favor of #21
