### ISSUE TITLE
Add support for TS v5's multiple config extensions

### ISSUE THREAD

**Issue by acidoxee** [privatenumber/get-tsconfig#44]
First of all, thanks a lot for your very helpful lib!

While tinkering with the TS v5 beta and preparing my monorepo for its coming changes, with [multiple config extensions among others](https://devblogs.microsoft.com/typescript/announcing-typescript-5-0-beta/#supporting-multiple-configuration-files-in-extends), I noticed most (if not all) of [`eslint-plugin-import`](https://github.com/import-js/eslint-plugin-import)'s rules were broken in my TS files, with the following error:

```
Resolve error: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received an instance of Array
    at new NodeError (node:internal/errors:399:5)
    at validateString (node:internal/validators:163:11)
    at Object.isAbsolute (node:path:1157:5)
    at be (/Users/acidoxee/Documents/projects/platform/node_modules/get-tsconfig/dist/index.cjs:3:7906)
    at J (/Users/acidoxee/Documents/projects/platform/node_modules/get-tsconfig/dist/index.cjs:3:9059)
    at J (/Users/acidoxee/Documents/projects/platform/node_modules/get-tsconfig/dist/index.cjs:3:9077)
    at Object.Te [as getTsconfig] (/Users/acidoxee/Documents/projects/platform/node_modules/get-tsconfig/dist/index.cjs:3:10154)
    at /Users/acidoxee/Documents/projects/platform/node_modules/eslint-import-resolver-typescript/lib/index.cjs:309:36
    at Array.map (<anonymous>)
    at initMappers (/Users/acidoxee/Documents/projects/platform/node_modules/eslint-import-resolver-typescript/lib/index.cjs:305:26)
```

As can be seen from the stacktrace, it originates from [`eslint-import-resolver-typescript`](https://github.com/import-js/eslint-import-resolver-typescript), which is what `eslint-plugin-import` recommends to support TS files. This package uses your lib to resolve one or several tsconfig files.

From just a quick glance, I'm guessing this function here (among other places) is where multiple config extensions' support is missing, since this function is expecting a single `requestedPath` as `string` instead of the new `string | string[]` format available in TS v5:

https://github.com/privatenumber/get-tsconfig/blob/d056db8616515bf2f16defa6e7cc65baca11b66e/src/parse-tsconfig/resolve-extends.ts#L28-L31

Would you be willing to add support for that feature to fully support TS v5? 🙏

**Comment by privatenumber** [comment]
Yeah, it should be supported.

Not sure when I'll have time to work on it but PR welcome!
