### ISSUE TITLE
Does not load "extends" files correctly from symlinked directories

### ISSUE THREAD

**Issue by inga-lovinde** [privatenumber/get-tsconfig#72]
### Problem

get-tsconfig resolves symlinks to real paths and uses resolved real paths as a base to resolve "extends" (this was implemented in https://github.com/privatenumber/get-tsconfig/pull/24).

This is incompatible with how TypeScript handles symlinks (it does not resolve symlinks).

As a result, when symlinked configs try to "extend" something from the origin directory, TypeScript loads extended files from the origin directory, while get-tsconfig produces a "File not found" error.

This is currently implemented in `_parseTsconfig` function:
https://github.com/privatenumber/get-tsconfig/blob/v4.7.3/src/parse-tsconfig/index.ts#L85-L90

### Expected behavior

I'd expect get-tsconfig to not produce errors, and instead to not resolve symlinks to real paths, just as TypeScript does.

### Minimal reproduction URL

https://stackblitz.com/edit/stackblitz-starters-gynqrn

TypeScript handles this config layout perfectly:
```
~/projects/stackblitz-starters-gynqrn/project
❯ tsc --showConfig
{
    "compilerOptions": {
        "outDir": "./dist",
        "rootDir": "./src",
        "noEmitOnError": false
    },
    "files": [
        "./src/index.ts"
    ],
    "include": [
        "config-template/../src"
    ]
}

~/projects/stackblitz-starters-gynqrn/project
❯ tsc --listEmittedFiles
TSFILE: /home/projects/stackblitz-starters-gynqrn/project/dist/index.js

```

get-tsconfig produces an error on encountering symlinked config which tries to extend from config located in the origin (non-symlinked) directory:
```
~/projects/stackblitz-starters-gynqrn
❯ node ./get-tsconfig-demo.js
Error: File '../tsconfig-custom-overrides.json' not found.
    at je (/home/projects/stackblitz-starters-gynqrn/node_modules/get-tsconfig/dist/index.cjs:3:9102)
    at te (/home/projects/stackblitz-starters-gynqrn/node_modules/get-tsconfig/dist/index.cjs:3:10068)
    at je (/home/projects/stackblitz-starters-gynqrn/node_modules/get-tsconfig/dist/index.cjs:3:9260)
    at te (/home/projects/stackblitz-starters-gynqrn/node_modules/get-tsconfig/dist/index.cjs:3:10068)
    at ie (/home/projects/stackblitz-starters-gynqrn/node_modules/get-tsconfig/dist/index.cjs:3:10783)
    at $e (/home/projects/stackblitz-starters-gynqrn/node_modules/get-tsconfig/dist/index.cjs:3:10888)
    at function (https://stackblitzstartersgynqrn-tzfv.w-corp-staticblitz.com/blitz.0314a412.js:352:196823)
    at Module.prototype._compile (node:internal/modules/cjs/loader:54:14871)
    at Module."] (node:internal/modules/cjs/loader:54:15550)
    at Module.prototype.load (node:internal/modules/cjs/loader:54:13457)
    at Module._load (node:internal/modules/cjs/loader:54:10535)
    at executeUserEntryPoint (node:internal/modules/run_main:125:731)
    at _0xd40aa0 (https://stackblitzstartersgynqrn-tzfv.w-corp-staticblitz.com/blitz.0314a412.js:350:56974)
    at _0x5c07a4 (https://stackblitzstartersgynqrn-tzfv.w-corp-staticblitz.com/blitz.0314a412.js:352:101852)
    at executeBootstrapper (https://stackblitzstartersgynqrn-tzfv.w-corp-staticblitz.com/blitz.0314a412.js:352:622137)
    at startExecution (https://stackblitzstartersgynqrn-tzfv.w-corp-staticblitz.com/blitz.0314a412.js:371:2925)
    at run (https://stackblitzstartersgynqrn-tzfv.w-corp-staticblitz.com/blitz.0314a412.js:371:1311)

```

### Version

v4.7.3

### Node.js version

v18.18.0

### Package manager

npm

### Operating system

Linux

### Contributions

- [ ] I plan to open a pull request for this issue
I would open a pull request, but I don't know why the original decision to resolve symlinks was made, so I don't know what will break if I were to disable resolving symlinks.

- [ ] I plan to make a financial contribution to this project

**Comment by privatenumber** [comment]
Thanks for reporting!

> I would open a pull request, but I don't know why the original decision to resolve symlinks was made, so I don't know what will break if I were to disable resolving symlinks.

It was probably an oversight. TypeScript behavior is the source of truth so any behavior that strays away from it is a bug. PR welcome!
